//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devlooped.OpenAI.Sponsors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sponsors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sponsors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Devlooped.OpenAI.Sponsors.Sponsors", typeof(Sponsors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for being part of team {0} with your contributions 💟!.
        /// </summary>
        internal static string Contributor_Message {
            get {
                return ResourceManager.GetString("Contributor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor status has expired and automatic sync has not been enabled..
        /// </summary>
        internal static string Expired_Message {
            get {
                return ResourceManager.GetString("Expired_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor status needs periodic updating and automatic sync has not been enabled..
        /// </summary>
        internal static string Expiring_Message {
            get {
                return ResourceManager.GetString("Expiring_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace period ends in {0} days. Enjoy and please consider supporting {1} by sponsoring {2} 🙏.
        /// </summary>
        internal static string Grace_Message {
            get {
                return ResourceManager.GetString("Grace_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for being an open source author 💟!.
        /// </summary>
        internal static string OpenSource_Message {
            get {
                return ResourceManager.GetString("OpenSource_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for supporting {0} with your sponsorship 💟!.
        /// </summary>
        internal static string Sponsor_Message {
            get {
                return ResourceManager.GetString("Sponsor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0} 💪.
        /// </summary>
        internal static string Team_Message {
            get {
                return ResourceManager.GetString("Team_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider supporting {0} by sponsoring {1} 🙏.
        /// </summary>
        internal static string Unknown_Message {
            get {
                return ResourceManager.GetString("Unknown_Message", resourceCulture);
            }
        }
    }
}
